name: Upload website to S3

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME : "resumecarrollbucket"
  AWS_REGION : "us-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-resume-front

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform-resume-front

      - name: List S3 Bucket Contents
        run: |
          aws s3 ls s3://resumecarrollbucket

      #- name: Import S3 Bucket
      #  run: terraform import aws_s3_bucket.resumeBucket resumebucketcarroll
      #  working-directory: terraform-resume-front

      #- name: Import Cloudfront Distro
      #  run: terraform import aws_cloudfront_distribution.resume_cf_distro E2E12TP6LTG1FT
      #  working-directory: terraform-resume-front

      - name: Plan Terraform deployment
        id: plan
        run: terraform plan -out=tfplan
        working-directory: terraform-resume-front

      - name: Apply Terraform configuration
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform-resume-front

      - name: Invalidate CloudFront Cache
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2E12TP6LTG1FT \
            --paths "/*"